export const GET_CLASSES = "GET_CLASSES";
export const CREATE_CLASS = "CREATE_CLASS";
export const GET_CLASS_BY_ID = "GET_CLASS_BY_ID";
export const DELETE_CLASS_BY_ID = "DELETE_CLASS_BY_ID";
export const UPDATE_CLASS_BY_ID = "UPDATE_CLASS_BY_ID";

export const GET_MODULES = "GET_MODULES";
export const CREATE_MODULE = "CREATE_MODULE";
export const GET_MODULE_BY_ID = "GET_MODULE_BY_ID";
export const DELETE_MODULE_BY_ID = "DELETE_MODULE_BY_ID";
export const UPDATE_MODULE_BY_ID = "UPDATE_MODULE_BY_ID";

export const GET_COURSES = "GET_COURSES";
export const CREATE_COURSE = "CREATE_COURSE";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const DELETE_COURSE_BY_ID = "DELETE_COURSE_BY_ID";
export const UPDATE_COURSE_BY_ID = "UPDATE_COURSE_BY_ID";

export const GET_USERS = "GET_USERS";
//export const CREATE_USER = "CREATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
//export const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
export const UPDATE_USER_BY_ID = "UPDATE_USER_BY_ID";

export const SIGN_IN_USER = "SIGN_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";

export const GET_MODULES_FROM_COURSE_BY_ID = "GET_MODULES_FROM_COURSE_BY_ID";
export const GET_CLASSES_FROM_MODULE_BY_ID = "GET_CLASSES_FROM_MODULE_BY_ID";

export const GET_ALL_COURSES_WITH_MODULES_AND_CLASSES = "GET_ALL_COURSES_WITH_MODULES_AND_CLASSES";
